### PR TITLE
Remove window min width and height

### PR DESCRIPTION
**Pull request by s-k-y-l-i**

### CODE REVIEW

**Comment by Sytten** [comment]
Thats not an upgrade at all

**Comment by s-k-y-l-i** [comment]
yes it is becouse with the limit, we can't set the width to small. In this version: http://messengerfordesktop.com/ i can make it small that way it doesn't even distrupt my game for example and still can talk my friend.

**Comment by Sytten** [comment]
You can do it for your own code, but for the everyday user this is a bug.

**Comment by s-k-y-l-i** [comment]
I dont think it was a bug. The default width is ok to be large, but it's a missing feature to not being able to resize it in my opinion. I tried to make my own build but the exe i got in the output was not working :/ I tried compiling on windows.
nevtelen-1

**Comment by Sytten** [comment]
I see, well you should set a smaller minimum then. That would be acceptable, but I dont have the time to do a release. Never tried compiling on windows, but on linux you can do it pretty easily (apart from creating the installer which is a pain in the a*s...)

**Comment by s-k-y-l-i** [comment]
Ok, I've changed it to the best fully working min width with slider on the screen too :) (317px instead of 600px)

**Comment by Sytten** [comment]
Good, I will merge it in the next release (maybe next weekend if I have time).

**Comment by nevercast** [comment]
Closed by https://github.com/Sytten/Facebook-Messenger-Desktop/commit/582cb0941fb178aa92b75723614ee9f3f1f690eb

**Pull request closed without merging**
